import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { normalizeBangladeshMobile } from "@/lib/order-validation";
import { rateLimit, requestIp } from "@/lib/rate-limit";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";
import { z } from "zod";
export const runtime = "nodejs";
const schema = z.object({ orderNumber: z.string().trim().min(5).max(50), mobile: z.string().trim().min(1).max(20), rating: z.coerce.number().int().min(1).max(5), displayName: z.string().trim().min(2).max(80), comment: z.string().trim().max(1000).optional() });
export async function POST(request: Request) { if (!rateLimit(`review:${requestIp(request)}`, 5, 60 * 60 * 1000)) return NextResponse.json({ error: "Too many review attempts. Please try again later." }, { status: 429 }); const multipart = request.headers.get("content-type")?.includes("multipart/form-data"); const form = multipart ? await request.formData() : null; const raw = form ? Object.fromEntries(form.entries()) : await request.json().catch(() => ({})); const parsed = schema.safeParse(raw); if (!parsed.success) return NextResponse.json({ error: "Please provide a valid rating, name, comment, order number, and mobile." }, { status: 400 }); const data = parsed.data; const order = await prisma.order.findFirst({ where: { orderNumber: data.orderNumber, mobile: normalizeBangladeshMobile(data.mobile), status: "DELIVERED" }, select: { id: true } }); if (!order) return NextResponse.json({ error: "Only a delivered order with the matching mobile can submit a review." }, { status: 403 }); const photo = form?.get("photo"); let photoPath: string | undefined; if (photo instanceof File && photo.size > 0) { if (photo.size > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp"].includes(photo.type)) return NextResponse.json({ error: "Photo must be JPEG, PNG, or WebP up to 5MB." }, { status: 400 }); const fileName = `${randomUUID()}.${photo.type.split("/")[1]}`; await mkdir(path.join(process.cwd(), "public", "uploads"), { recursive: true }); await writeFile(path.join(process.cwd(), "public", "uploads", fileName), Buffer.from(await photo.arrayBuffer())); photoPath = `/uploads/${fileName}`; } try { const review = await prisma.review.create({ data: { orderId: order.id, customerName: data.displayName, displayName: data.displayName, rating: data.rating, comment: data.comment || null, photoPath, verifiedBuyer: true, status: "PENDING", isApproved: false } }); return NextResponse.json({ ok: true, reviewId: review.id }); } catch { return NextResponse.json({ error: "This order already has a review or could not be reviewed." }, { status: 409 }); } }
