import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { normalizeBangladeshMobile, orderCaptureSchema } from "@/lib/order-validation";
import { rateLimit, requestIp } from "@/lib/rate-limit";
import { calculatePricing } from "@/lib/pricing";
export const runtime = "nodejs";
export async function POST(request: Request) {
  if (!rateLimit(`order:${requestIp(request)}`, 10, 60 * 60 * 1000)) return NextResponse.json({ error: "Too many order attempts. Please try again later." }, { status: 429 });
  try { const form = await request.formData(); const parsed = orderCaptureSchema.safeParse(Object.fromEntries(form.entries())); if (!parsed.success) return NextResponse.json({ error: "Please correct your order details.", fields: parsed.error.flatten().fieldErrors }, { status: 400 }); const data = parsed.data; const settings = await prisma.bookSettings.findFirst(); if (!settings) return NextResponse.json({ error: "Book settings are not configured." }, { status: 500 }); const pricing = calculatePricing(settings); const post = data.plan === "PREPAID_350"; const deliveryType = post ? "BANGLADESH_POST" : "COURIER"; const total = post ? pricing.postTotal : pricing.courierTotal; const deliveryCharge = post ? pricing.postDeliveryCharge : pricing.courierDeliveryCharge; const payNow = post ? pricing.postPayNow : pricing.courierPayNow; const now = new Date(); const date = `${String(now.getFullYear()).slice(-2)}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}`; const number = `BG-${date}-${String((await prisma.order.count()) + 1).padStart(5, "0")}`; const order = await prisma.$transaction((tx) => tx.order.create({ data: { orderNumber: number, customerName: data.customerName, mobile: normalizeBangladeshMobile(data.mobile), alternateMobile: null, email: null, division: null, district: data.district, upazilaOrThana: data.upazilaOrThana, unionOrWard: null, areaOrVillage: data.fullAddress, roadOrStreet: null, houseOrHolding: null, postOffice: null, postalCode: data.postalCode || null, landmark: null, deliveryInstruction: null, deliveryType, paymentPlan: data.plan, status: "AWAITING_PAYMENT", subtotal: pricing.bookPrice, deliveryCharge, grandTotal: total, payNowAmount: payNow, paidAmount: 0, dueAmount: post ? pricing.postDue : pricing.courierDue, items: { create: { title: settings.title, quantity: 1, unitPrice: pricing.bookPrice, totalPrice: pricing.bookPrice } } } })); return NextResponse.json({ orderNumber: order.orderNumber, payNow }); } catch (error) { console.error("order capture failed", error); return NextResponse.json({ error: "Unable to save this order. Please try again." }, { status: 500 }); }
}
